/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package main */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "c_bind.go"


typedef struct YdbConnection {} YdbConnection;
typedef struct YdbResult {} YdbResult;

#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern struct YdbConnection* ydb_connect(char* connectionString, int connectionStringLen);
extern int ydb_connect_has_result(struct YdbConnection* connection);
extern int ydb_connect_wait(struct YdbConnection* connection);
extern void ydb_connect_free(struct YdbConnection* connection);
extern struct YdbResult* ydb_query(struct YdbConnection* connection, char* query, int queryLen);
extern void ydb_result_free(struct YdbResult* res);
extern int ydb_result_has_result(struct YdbResult* res);
extern void ydb_result_wait(struct YdbResult* res);
extern int ydb_result_has_errors(struct YdbResult* res);
extern int ydb_result_next_readset(struct YdbResult* res);
extern int ydb_result_next_row(struct YdbResult* res);
extern int ydb_result_read_first_field_text(struct YdbResult* res, void* dstBuffer, int dstBufferLen);
extern int ydb_check_linked_library();

#ifdef __cplusplus
}
#endif
